docker-sniffles2
cuhk-haosun/code-docker-sniffles2 pull request #1
Opened 2024-10-15 03:11 UTC by 223050025

2024-10-16 06:11 UTC, Milokita requested changes

2024-10-16 06:11 UTC, Milokita commented on .github/workflows/docker-publish-github.yml
pls also add docker push to the dockerhub

2024-10-16 06:11 UTC, Milokita commented on entrypoint.sh
great

2024-10-16 06:11 UTC, Milokita commented on Dockerfile
nicely done

2024-10-18 13:46 UTC, 223050025 commented
1. Try to add Docker Hub login information and add Docker Hub push step.
2. Meet problem in log into docker hub: Error Username and password required.

@Milokita

2024-10-18 23:53 UTC, Milokita requested changes

2024-10-18 23:53 UTC, Milokita commented on .github/workflows/docker-publish-github.yml
> +          tags: ${{ steps.meta.outputs.tags }}
Tag : **latest** seems missing

2024-10-18 23:53 UTC, Milokita commented on Dockerfile
> +# Add Bismark to PATH
Bismark ?

2024-10-19 02:48 UTC, 223050025 commented on .github/workflows/docker-publish-github.yml
> +          tags: ${{ steps.meta.outputs.tags }}
65 line: change to tags: cuhkhaosun/sniffles2:latest

2024-10-19 03:03 UTC, 223050025 commented on .github/workflows/docker-publish-github.yml
> +          tags: ${{ steps.meta.outputs.tags }}
Merge Docker build steps and push both to GitHub Container Registry (ghcr.io) and to Docker Hub

2024-10-19 03:05 UTC, 223050025 commented
Still problem: log into docker hub: Error Username and password required.
@Milokita

2024-10-22 02:19 UTC, Milokita approved these changes

2024-10-22 02:19 UTC, merged